apiVersion: config.openshift.io/v1
kind: Plugin
metadata:
  labels:
    app.kubernetes.io/name: plugin
    app.kubernetes.io/instance: plugin-sample
    app.kubernetes.io/part-of: cli-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cli-manager
  name: plugin-sample
spec:
  # TODO(user): Add fields here
